services:
    termio:
        build:
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'termio-sail-8.4/app'
        container_name: termio-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8082}:80'
            - '${VITE_PORT:-5184}:${VITE_PORT:-5184}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - termio-sail
        depends_on:
            - termio-pgsql
            - termio-mailpit
    termio-mailpit:
        image: 'axllent/mailpit:latest'
        container_name: termio-mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1035}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8035}:8025'
        networks:
            - termio-sail
    termio-pgsql:
        image: 'postgres:17'
        container_name: termio-pgsql
        ports:
            - '${FORWARD_DB_PORT:-5443}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'termio-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - termio-sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
networks:
    termio-sail:
        driver: bridge
volumes:
    termio-pgsql:
        driver: local
